# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LeonBjorklund.Portside
PackageVersion: 1.0.1
MinimumOSVersion: 10.0.22000.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
UnsupportedOSArchitectures:
- arm64
ProductCode: '{AFF72E51-A6A3-43E6-A6A4-71C15C264409}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/leonbjorklund/portside/releases/download/v1.0.1/Portside-1.0.1-x64-setup.exe
  InstallerSha256: '02E5C90AAAA7B9A26ACAA3AB8643F4154F7433BDE8F76865A1044E51A5741B3D'
ManifestType: installer
ManifestVersion: 1.12.0
